theme: minima
title: An 0ld Camel's Journey in Finding the Perfect School
author: 0ld Camel
email: 0ldcamel502@gmail.com
description: Finding the Perfect School, one school at a time.
url: https://0ldcamel.github.io/blog

github_username: 0ldcamel
twitter_username: 0IdCamel


